use_frameworks!

target 'OKTextFieldView_Example' do
  pod 'OKTextFieldView', :path => '../'
  pod 'OKActiveButton', '~> 0.1.0'
  pod 'AKNumericFormatter', '~> 0.0.2'
  

  target 'OKTextFieldView_Tests' do
    inherit! :search_paths

    
  end
end
